all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
- - 8
- - 9
- - 10
- - 11
- - 12
- - 13
- - 14
- - 15
- - 16
- - 17
- - 18
- - 19
- - 20
- - 21
- - 22
- - 23
- - 24
- - 25
- - 26
- - 27
- - 28
- - 29
- - 30
- - 31
all_joints_names:
- thumb_tip
- thumb_PIJ
- thumb_knuckle
- index_tip
- index_DIJ
- index_PIJ
- index_knuckle
- middle_tip
- middle_DIJ
- middle_PIJ
- middle_knuckle
- ring_tip
- ring_DIJ
- ring_PIJ
- ring_knuckle
- pinky_tip
- pinky_DIJ
- pinky_PIJ
- pinky_knuckle
- wrist
- forearm
- elbow
- upper_arm
- shoulder
- keypoint0
- keypoint1
- keypoint2
- keypoint3
- keypoint4
- keypoint5
- keypoint6
- keypoint7
alpha_r: 0.02
apply_prob: 0.5
batch_size: 1
contrast:
  clahe: true
  claheratio: 0.1
  histeq: true
  histeqratio: 0.1
convolution:
  edge: false
  emboss:
    alpha:
    - 0.0
    - 1.0
    strength:
    - 0.5
    - 1.5
  embossratio: 0.1
  sharpen: false
  sharpenratio: 0.3
cropratio: 0.4
dataset: training-datasets\iteration-0\UnaugmentedDataSet_NATALYA_20200723Jul9\NATALYA_20200723_Neekon
  Saadat95shuffle1.mat
dataset_type: albumentations
decay_steps: 30000
display_iters: 1000
engine: pytorch
global_scale: 0.8
init_weights: C:\Users\Phoenix\Anaconda3\envs\DLC_NEEKON_v2.3.10\lib\site-packages\deeplabcut
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 0.0005
max_input_size: 1500
metadataset: training-datasets\iteration-0\UnaugmentedDataSet_NATALYA_20200723Jul9\Documentation_data-NATALYA_20200723_95shuffle1.pickle
min_input_size: 64
mirror: false
multi_stage: false
multi_step:
- - 0.005
  - 10000
- - 0.02
  - 430000
- - 0.002
  - 730000
- - 0.001
  - 1030000
net_type: resnet_101
num_joints: 32
pairwise_huber_loss: false
pairwise_predict: false
partaffinityfield_predict: false
pos_dist_thresh: 17
project_path: D:\Data\Neekon_S\git\POSE_EVENT_MARK\DeepLabCut Project\NATALYA_20200723-Neekon
  Saadat-2024-07-09
rotation: 25
rotratio: 0.4
save_iters: 50000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
