data:
  colormode: RGB
  inference:
    normalize_images: true
  train:
    affine:
      p: 0.5
      rotation: 30
      scaling:
      - 1.0
      - 1.0
      translation: 0
    collate:
      type: ResizeFromDataSizeCollate
      min_scale: 0.4
      max_scale: 1.0
      min_short_side: 128
      max_short_side: 1152
      multiple_of: 32
      to_square: false
    covering: false
    gaussian_noise: 12.75
    hist_eq: false
    motion_blur: false
    normalize_images: true
device: auto
metadata:
  project_path: D:\Data\Neekon_S\git\POSE_EVENT_MARK\DeepLabCut Project\NATALYA_20200723-Neekon
    Saadat-2024-07-09
  pose_config_path: D:\Data\Neekon_S\git\POSE_EVENT_MARK\DeepLabCut Project\NATALYA_20200723-Neekon
    Saadat-2024-07-09\dlc-models-pytorch\iteration-0\NATALYA_20200723Jul9-trainset95shuffle1\train\pose_cfg.yaml
  bodyparts:
  - thumb_tip
  - thumb_PIJ
  - thumb_knuckle
  - index_tip
  - index_DIJ
  - index_PIJ
  - index_knuckle
  - middle_tip
  - middle_DIJ
  - middle_PIJ
  - middle_knuckle
  - ring_tip
  - ring_DIJ
  - ring_PIJ
  - ring_knuckle
  - pinky_tip
  - pinky_DIJ
  - pinky_PIJ
  - pinky_knuckle
  - wrist
  - forearm
  - elbow
  - upper_arm
  - shoulder
  - keypoint0
  - keypoint1
  - keypoint2
  - keypoint3
  - keypoint4
  - keypoint5
  - keypoint6
  - keypoint7
  unique_bodyparts: []
  individuals:
  - animal
  with_identity:
method: bu
model:
  backbone:
    type: ResNet
    model_name: resnet101
    output_stride: 16
    freeze_bn_stats: true
    freeze_bn_weights: false
  backbone_output_channels: 2048
  heads:
    bodypart:
      type: HeatmapHead
      weight_init: normal
      predictor:
        type: HeatmapPredictor
        apply_sigmoid: false
        clip_scores: true
        location_refinement: true
        locref_std: 7.2801
      target_generator:
        type: HeatmapGaussianGenerator
        num_heatmaps: 32
        pos_dist_thresh: 17
        heatmap_mode: KEYPOINT
        generate_locref: true
        locref_std: 7.2801
      criterion:
        heatmap:
          type: WeightedMSECriterion
          weight: 1.0
        locref:
          type: WeightedHuberCriterion
          weight: 0.05
      heatmap_config:
        channels:
        - 2048
        - 32
        kernel_size:
        - 3
        strides:
        - 2
      locref_config:
        channels:
        - 2048
        - 64
        kernel_size:
        - 3
        strides:
        - 2
net_type: resnet_101
runner:
  type: PoseTrainingRunner
  gpus:
  key_metric: test.mAP
  key_metric_asc: true
  eval_interval: 1
  optimizer:
    type: AdamW
    params:
      lr: 0.0001
  scheduler:
    type: LRListScheduler
    params:
      lr_list:
      - - 1e-05
      - - 1e-06
      milestones:
      - 160
      - 190
  snapshots:
    max_snapshots: 5
    save_epochs: 50
    save_optimizer_state: false
train_settings:
  batch_size: 1
  dataloader_workers: 0
  dataloader_pin_memory: true
  display_iters: 1000
  epochs: 200
  seed: 42
