[package]
name = "overlay_posture_from_csv"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
ffmpeg-next = "7.0.2"
image = "0.25.1"
indicatif = "0.17.8"
clap = { version = "4.0", features = ["derive"] }